#!/usr/bin/env python
import mechanize
br=mechanize.Browser()
br.set_handle_robots(False)   # ignore robots
br.set_handle_refresh(False)  # can sometimes hang without this
br.addheaders =  [('User-agent', 'Firefox')]
response=br.open('http://192.168.100.1/RgConfig.asp')
forms=mechanize.ParseResponse(response, backwards_compat=False)
#for f in forms:
#	print f
br.select_form(name="RgConfig")
form=forms[0]
br.find_control("ResetReq").readonly=False
#form.find_control("<None>=Restart Cable Modem").readonly=False
br["ResetReq"]="1"
#print form
response=br.submit()
